return {
  [1] = {
    size = {3, 7},
    objs = {
      {'obstacle', 0, 5},
      {'obstacle', 0, 6},
      {'obstacle', 1, 1},
      {'bloom', 0, 3},
      {'bloom', 0, 0},
      {'bloom', 2, 5},
      {'pollen', 1, 4, group = 1},
      {'pollen', 1, 3, group = 1},
      {'pollen', 2, 3, group = 2},
      {'pollen', 2, 4, group = 2},
      {'butterfly', 1, 6, dir = 2},
    },
  },
  [2] = {
    size = {5, 5},
    objs = {
      {'reflect_obstacle', 4, 0},
      {'bloom', 2, 1},
      {'bloom', 1, 3},
      {'pollen', 0, 2, group = 1},
      {'pollen', 1, 2, group = 1},
      {'pollen', 2, 3, group = 2},
      {'pollen', 2, 4, group = 2},
      {'butterfly', 3, 4, dir = 3},
      {'butterfly', 4, 4, dir = 3},
    },
  },
  [3] = {
    size = {4, 7},
    objs = {
      {'obstacle', 3, 0},
      {'obstacle', 3, 1},
      {'bloom', 3, 3},
      {'bloom', 2, 4},
      {'bloom', 3, 4},
      {'weeds', 2, 3},
      {'pollen', 0, 3, group = 1},
      {'pollen', 1, 3, group = 1},
      {'pollen', 2, 0, group = 2},
      {'pollen', 2, 1, group = 2},
      {'pollen', 2, 5, group = 3},
      {'pollen', 2, 6, group = 3},
      {'butterfly', 1, 2, dir = 1},
    },
  --[[
    size = {3, 6},
    objs = {
      {'bloom', 1, 0},
      {'bloom', 2, 0},
      {'bloom', 2, 1},
      {'bloom', 1, 5},
      {'weeds', 1, 1},
      {'pollen', 0, 3, group = 1},
      {'pollen', 0, 4, group = 1},
      {'pollen', 1, 3, group = 2},
      {'pollen', 1, 4, group = 2},
      {'pollen', 2, 3, group = 3},
      {'pollen', 2, 4, group = 3},
      {'butterfly', 0, 2, dir = 2},
    },
  ]]
  },
}
